name: CI - Linux/OSX/Windows - Conda

on:
  # push:
  # pull_request:
  release:

jobs:
  build-with-conda:
    name: '[conda:${{ matrix.os }}:${{ matrix.build_type }}]'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        build_type: [Release, Debug]
        name: [ubuntu-latest, macos-latest, windows-latest-clang-cl]

        include:
          - name: ubuntu-latest
            os: ubuntu-latest
          - name: macos-latest
            os: macos-latest
          - name: windows-latest-clang-cl
            os: windows-2019
            compiler: clang-cl

    steps:
    - uses: actions/checkout@v2

    - uses: conda-incubator/setup-miniconda@v2
      with:
        miniforge-variant: Mambaforge
        miniforge-version: latest
        channels: conda-forge
        python-version: "3.10"
        activate-environment: proxsuite

    - name: Install dependencies [Conda]
      shell: bash -l {0}
      run: |
        # Workaround for https://github.com/conda-incubator/setup-miniconda/issues/186
        conda config --remove channels defaults
        # Compilation related dependencies
        mamba install cmake compilers make pkg-config doxygen ninja graphviz
        # Main dependencies
        mamba install eigen simde
        # Test dependencies
        mamba install libmatio numpy scipy

    - name: Install julia [macOS/Linux]
      if: contains(matrix.os, 'macos') || contains(matrix.os, 'ubuntu')
      shell: bash -l {0}
      run: |
        mamba install julia

    - name: Activate ccache [Conda]
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        key: ${{ matrix.os }}-${{ matrix.type }}
        max-size: 1G

    - name: Print environment [Conda]
      shell: bash -l {0}
      run: |
        conda info
        mamba list
        env

    - name: Configure [Conda/Linux&macOS]
      if: contains(matrix.os, 'macos') || contains(matrix.os, 'ubuntu')
      shell: bash -l {0}
      run: |
        echo $(whereis ccache)
        echo $(which ccache)
        git submodule update --init
        mkdir build
        cd build
        cmake .. -GNinja -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_INSTALL_PREFIX=${CONDA_PREFIX} -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DBUILD_PYTHON_INTERFACE:BOOL=ON -DPYTHON_EXECUTABLE=$(which python3) -DINSTALL_DOCUMENTATION:BOOL=ON -DTEST_JULIA_INTERFACE:BOOL=ON

    - name: Configure [Conda/Windows]
      if: contains(matrix.os, 'windows')
      shell: bash -l {0}
      run: |
        echo $(where ccache)
        git submodule update --init
        mkdir build
        cd build
        cmake .. -G"Visual Studio 16 2019" -T "ClangCl" -DCMAKE_GENERATOR_PLATFORM=x64 -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_INSTALL_PREFIX=${CONDA_PREFIX}/Library -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}  -DBUILD_PYTHON_INTERFACE:BOOL=ON -DPYTHON_SITELIB=${CONDA_PREFIX}/Lib/site-packages -DPYTHON_EXECUTABLE=${CONDA_PREFIX}/python.exe -DINSTALL_DOCUMENTATION:BOOL=ON

    - name: Build [Conda]
      shell: bash -l {0}
      run: |
        cd build
        cmake --build . --config ${{ matrix.build_type }} -v

    - name: Build documentation [Conda]
      shell: bash -l {0}
      run: |
        cd build
        cmake --build . --config ${{ matrix.build_type }} --target doc

    - name: Install [Conda]
      shell: bash -l {0}
      run: |
        cd build
        cmake --install . --config ${{ matrix.build_type }}

    - name: Test [Conda]
      shell: bash -l {0}
      run: |
        find $CONDA_PREFIX -name proxsuite*
        python -c "import proxsuite"
        cd build
        ctest --output-on-failure -C ${{ matrix.build_type }}
    # - name: Test pkg-config [Conda]
    #   shell: bash -l {0}
    #   run: |
    #     cd build
    #     export PKG_CONFIG_PATH=$CONDA_PREFIX/lib/pkgconfig
    #     pkg-config --cflags proxsuite
    #     g++ -std=c++17 examples/cpp/overview-simple.cpp -o overview-simple $(pkg-config --cflags proxsuite)
    #     ./overview-simple

    # - name: Test CMake pacakging [Conda]
    #   shell: bash -l {0}
    #   run: |
    #     cd build
    #     g++ -std=c++17 examples/cpp/overview-simple.cpp -o overview-simple $(pkg-config --cflags proxsuite)
    #     ./overview-simple

    - name: Uninstall [Conda]
      shell: bash -l {0}
      run: |
        cd build
        cmake --build . --config ${{ matrix.build_type }} --target uninstall

    - name: Display ccache statistics [Conda]
      shell: bash -l {0}
      run: |
        echo $(ccache -s)